### ISSUE TITLE
To update membership form in home page

### ISSUE THREAD

**Issue by ORKO06** [dscnitrourkela/project-banana#143]
**Describe the bug**
The typeform to apply for membership is not opening

**To Reproduce**
1. Go to 'Home page'
2. Click on 'Apply for Membership button'

**Expected behavior**
A  typeform should have opened

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/126763358-4d40014d-fd63-44c1-96d3-3cfb173f9e27.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhibhaw** [comment]
@ORKO06 please do the necessary changes as required... Assigning the same to you
