### ISSUE TITLE
Add New Members to Team Section

### ISSUE THREAD

**Issue by HarishTeens** [dscnitrourkela/project-banana#90]
## Members List

- [x] Sriram Patibanda
- [x] Abhibhaw Asthana
- [x] Ankit Samota
- [x] Astha Nayak
- [x] Ritesh Patil
- [x] Manikandan Loganadin

### Details Template
- GitHub: 
- LinkedIn: 
- Facebook:
- Twitter:

**Note:** 
Find the Profile Pictures on Firebase Storage. Send the PR to **Master** Branch.

**Comment by abhibhaw** [comment]
# Details
- [Github](https://github.com/abhibhaw)
- [LinkedIn](https://www.linkedin.com/in/abhibhaw)
- [Facebook](https://www.facebook.com/iamabhibhaw)
- [Twitter](https://twitter.com/imabhibhaw)

**Comment by SriramPatibanda** [comment]
@HarishTeens I would like to take up this issue.

**Comment by nayakastha** [comment]
**Details**

- [GitHub](https://github.com/nayakastha)

- [LinkedIn](https://www.linkedin.com/in/astha-nayak-90b98a1a3)

- [Facebook](https://www.facebook.com/astha.nayak.92)

**Comment by aksamota** [comment]
- [GitHub](github.com/ankitkumarsamota121)
- [LinkedIn](linkedin.com/in/ankitkumarsamota121)

**Comment by SriramPatibanda** [comment]
> * [GitHub](github.com/ankitkumarsamota121)
> * [LinkedIn](linkedin.com/in/ankitkumarsamota121)

Wrong links bro, please check them once and send the correct ones

**Comment by Manikandan9206** [comment]
`
<ul>
  <li href='https://github.com/Manikandan9206' target='_blank>GitHub</li>
  <li href='https://www.linkedin.com/in/manikandan9206/' target='_blank>LinkedIn</li>
  <li href='https://twitter.com/manikandan9206' target='_blank>Twitter</li>
</ul>
`

**Comment by Manikandan9206** [comment]
`<ul>
  <li href='https://github.com/Manikandan9206' target='_blank>GitHub</li>
  <li href='https://www.linkedin.com/in/manikandan9206/' target='_blank>LinkedIn</li>
  <li href='https://twitter.com/manikandan9206' target='_blank>Twitter</li>
</ul>`

**Comment by Manikandan9206** [comment]
[GitHub](https://github.com/Manikandan9206)
[LinkedIn](https://www.linkedin.com/in/manikandan9206/)
[Twitter](https://twitter.com/manikandan9206)

**Comment by riteshsp2000** [comment]
[Twitter](https://twitter.com/riteshp2000)
[LinkedIn](https://www.linkedin.com/in/ritesh-patil-6049631a0/)
[GitHub](https://github.com/riteshsp2000)

**Comment by DesignrKnight** [comment]
Close this?
