### ISSUE TITLE
Sync branches and setup Feature Peek

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-banana#93]
- [ ] Sync master and release
- [ ] Setup Feature Peek
- [x] Add branch protection for master
- [x] Delete old branches that are not needed

All upcoming PRs should be to sent to master from forks
Pushes to release should only be from the master. Never from forks (unless it is a hotfix)
Once changes are pushed to release, send PR from release to master to sync. So master should always be ahead of release

**Comment by DesignrKnight** [comment]
@SriramPatibanda @riteshsp2000 
Anyone wants to take this up?

**Comment by DesignrKnight** [comment]
> @SriramPatibanda @riteshsp2000
> Anyone wants to take this up?

**Comment by SriramPatibanda** [comment]
Oopsie! I will do it after 2 days, not having my pc with me rn.

**Comment by DesignrKnight** [comment]
Sure Sure

**Comment by DesignrKnight** [comment]
Hey, do finish sometime soon

**Comment by DesignrKnight** [comment]
**Update**

Moving away from release branch workflow. Have updated GitHub Actions It will run on a new release. As it is a static website as we do not have parallel work on release and master simultaneously, this flow will work for us. 

How to trigger push to the website?
Create a new GitHub release and that would trigger the workflow. Single branch, multiple releases. This is the new flow

https://github.com/dscnitrourkela/project-banana/commit/f8b2a43c72e7571141f3b9f02c33dfb505b3cbb7

**Comment by riteshsp2000** [comment]
Is Feature Peak still needed for this? 
Considering that we can set up a preview channel on firebase and can handle it using Github Actions?

Apart from setting up GitHub Actions, I don't think anything else is needed?

Expanding on what @DesignrKnight said,
- Setup an action to trigger a deployment after a new release is created (Production Deploy)
- Setup an action to trigger a deployment on each new Pull Request (PR Deploy)

For now, these 2 should do the job well.

**Comment by abhibhaw** [comment]
@riteshsp2000 we already have an action for deployment after a new release is created.
Only PR one is needed then!!

**Comment by DesignrKnight** [comment]
Also, a note- > this is the website that will be archived after we switch completely to project-huckleberry

**Comment by abhibhaw** [comment]
Sad to say feature peak is no more 🗡️
